/*
 * This source file was generated by the Gradle 'init' task
 */
package org.javacode;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    }
}
