/*
 * This source file was generated by the Gradle 'init' task
 */
package org.javacode;

import org.javacode.patterns.prefixsum.ContiguousArray;

import java.util.concurrent.Executors;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    }
}
